### ISSUE TITLE
Fix errant NaNs in dataset

### ISSUE THREAD

**Issue by magsol** [quinngroup/Twitter-Embedding-Analysis#16]
Single NaN was found in a file in cluster 11. Quick fix was made (confirm @sking115422) because it was crashing the preprocessing. There is Regex that supposedly checks for NaNs wasn't catching this particular one.

Further investigation for other NaNs, and a more thorough fix (pandas DataFrames have great utilities for this), needs to be implemented.

**Comment by njj67229** [comment]
The file in question is cluster11/20140101-20161231_rabrq4kz7j_2015_11_26_14_30_activities.json.gz, we moved it out for running preprocessing

**Comment by sking115422** [comment]
Steps to Fix This Issue:

-Look at JSON to figure out why its different
-Once we identify difference we can figure out how it is slipping through
-Add in an check for NaN values in "restructure_data" file
