### ISSUE TITLE
Identify keywords in the finished PPMI model

### ISSUE THREAD

**Issue by magsol** [quinngroup/Twitter-Embedding-Analysis#17]
What are the interesting words? What are the words to be used for downstream analysis?

Seems that some specific keywords (e.g., HIV, AIDS, etc) don't make it into the top 10,000 most common words, which is apparently all that the PPMI model building will incorporate.

Hand-pick a good set of words that are definitely in the top 10,000.

**Comment by njj67229** [comment]
Used words from the medical word list [here](https://github.com/glutanimate/wordlist-medicalterms-en) that appear at least 10 times in our vocab. This is initial and will be fined tune in time

**Comment by njj67229** [comment]
Using our handpicked list of HIV terms
