### ISSUE TITLE
Create project milestones

### ISSUE THREAD

**Issue by magsol** [quinngroup/Twitter-Embedding-Analysis#20]
We have at least 3:
 - performance (measurement, improvement, QC and code reviews)
 - model comparisons and baselines
 - PPMI construction and deployment

Any others?

**Comment by magsol** [comment]
Also set priorities for each milestone. Then set up tickets and make assignments.

**Comment by sking115422** [comment]
I started trying to create some today. Let me know if you guys can think of any other ones. If not we can close this issue out for now and just add them as needed.
