### ISSUE TITLE
Speed up PPMI Runtime with Multi-Threading

### ISSUE THREAD

**Issue by sking115422** [quinngroup/Twitter-Embedding-Analysis#22]
This is probably highest priority so we can test the model more effectively and in less time.

**Comment by njj67229** [comment]
I've written up a multiprocessing solution that writes n chunks of the ppmi matrix to the disk for n cores, and then merges it together into one after. Not too space efficient but still much faster, I'd like to meet once to see if we can get it a little faster before closing this issue

**Comment by njj67229** [comment]
Multiprocessed!
