### ISSUE TITLE
Get Codespaces Up and Running

### ISSUE THREAD

**Issue by sking115422** [quinngroup/Twitter-Embedding-Analysis#26]
Been having issues getting a codespace enviorment set up and working. Looks like it is not an option currently.

**Comment by sking115422** [comment]
I have tried on my own to set it up, and we just tried as a group today. We can access the .dev and the VScode enviroment through github, but when we try to create a codespace and actually run something it just keeps telling us we need to download and run it locally. I am not sure if we have just not configured something correctly on GitHub or this feature have just not become avaliable to us yet. 

Its honestly probably something small we are missing, and then I am sure it will work fine.

**Comment by magsol** [comment]
This seems like a relevant page https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/setting-up-your-python-project-for-codespaces

**Comment by sking115422** [comment]
![image](https://user-images.githubusercontent.com/63437172/137547853-3e84a828-89b4-4c89-8016-d0b6f0fd6660.png)

I am not seeing the option to create a new codespace.

**Comment by magsol** [comment]
Don't worry, I set a spending limit :) Definitely go smaller as you're initially trying things out. Once we have a feel for what we need we can reassess.

**Comment by sking115422** [comment]
I am going to close this issue bc we have all confirmed that github codespaces is working for all of us.
