### ISSUE TITLE
Speed Up Co-Occurence

### ISSUE THREAD

**Issue by sking115422** [quinngroup/Twitter-Embedding-Analysis#28]
Possible decrease nesting structure or find some other way to help "populate_cooccurence" run faster

**Comment by njj67229** [comment]
This is the biggest bottleneck in our code right now

**Comment by njj67229** [comment]
model/populate_cooccurence.py
The populate_ppmi.py script has a solution that we can probably implement to this file easily

**Comment by magsol** [comment]
Sex-tuple for loop https://github.com/quinngroup/Twitter-Embedding-Analysis/blob/master/model/populate_cooccurrence.py#L11

**Comment by njj67229** [comment]
Switched to using cooccurrence script in preprocessing for now, and switched the ordering of the for loops to iterate all tweets just once. Run time reduced by several 100%. I'll close this in the coming days once I update populate_cooc to match
