### ISSUE TITLE
Study/Inverstigate if There Are Any Prebuilt PPMI Libraries

### ISSUE THREAD

**Issue by sking115422** [quinngroup/Twitter-Embedding-Analysis#30]
I am not sure if any prebuilt PPMI libraries exist, but  if we could find one we could see how they have organized thing, and it may help us to find way to optimize our own code.

**Comment by magsol** [comment]
You probably won't find something that precisely implements the PPMI algorithm you're referencing, BUT you may find a lot of things that implement parts of it.

For instance, Python's built-in [Counter collection](https://docs.python.org/3/library/collections.html#collections.Counter) will pretty much do basic word counting all by itself (once words have been correctly preprocessed and tokenized). The [`nltk`](https://www.nltk.org/) package has a ton of tokenization and text preprocessing strategies already built-in. These can probably get you most of the way there.

**Comment by njj67229** [comment]
PPMI generation is well optimized now
