### ISSUE TITLE
Reimplement util code

### ISSUE THREAD

**Issue by njj67229** [quinngroup/Twitter-Embedding-Analysis#40]
When daniel got reset I think we lost some of the util code used in alignment.py and svd.py that we need to reimplement before we can generate a model.

**Comment by njj67229** [comment]
If I recall correctly we were able to pull most of it off of the repo from the original paper: https://github.com/yifan0sun/DynamicWord2Vec

**Comment by magsol** [comment]
What did the code do?

**Comment by njj67229** [comment]
I've got to go through the alignment.py script again but I believe it had a few methods that were used for alignment and minimizing our loss functions

**Comment by njj67229** [comment]
https://github.com/yifan0sun/DynamicWord2Vec/blob/master/train_model/util_timeCD.py
https://github.com/yifan0sun/DynamicWord2Vec/blob/master/train_model/train_time_CD_smallnyt.py

The train_time_CD script is our alignment.py script but I believe we are missing the util_timeCD.py

**Comment by magsol** [comment]
What does `timeCD.py` do? Is that script timing, or timestamp conversions, or something else?

**Comment by njj67229** [comment]
It's involved in managing the different temporal chunks of our vocab and embeddings. It's been a while since I've looked at this or the alignment script but it uses most of the functions in here. I'm doing a bit of refreshing and trying to understand what all of it does. If my memory is right, and I'll reach out to Zane to confirm, we had a beta version of a working alignment last spring that we never tested on anything other than a few test matrices. But right now, from the looks of it, I'm thinking we need to rewrite these scripts pretty heavily

**Comment by magsol** [comment]
Sounds about right. We can discuss this on Friday at our project status meeting.
